lawyer/urls.py
from django.urls import path
from . import account_view, core_views, contact_view, gestion_active_views

app_name = "lawyer"
urlpatterns = [
    #account urls
    path('account/login/', account_view.login_view, name='login'),
    path('account/register/', account_view.register_view, name='register'),

    # other paths can be added here
    # core views
    path('core/', core_views.index, name='index'),

    # contact views
    path('contact/list_personne/', contact_view.contact_personne, name='contact_personne'),
    path('contact/details_personne/', contact_view.details_contact_personne, name='detail_contact_personne'),


    #gestion des activites
    path('settings/gestion_active/', gestion_active_views.gestion_active_views, name='gestion_active'),
    path('settings/add_type_activiter/', gestion_active_views.add_type_activiter, name='add_type_activiter'),
    path('settings/details_type_active/<int:id>/', gestion_active_views.details_type_active,name='details_type_active'),
    path('settings/details_type_active/active_champs_types/<int:id>/<int:champs_id>',
         gestion_active_views.active_champs_types,name='active_champs_types'),

    path('settings/details_type_active/active_champs_types/categories/<int:id>/',
         gestion_active_views.add_categorie_activity,name='add_categorie_activity'),

]

todo/urls.py
from django.urls import path

from .views import (todo_list, todo_detail, todo_create, todo_update, todo_validate, todo_complete)

app_name = 'todo'

urlpatterns = [
    path('', todo_list, name='todo_list'),
    path('<int:todo_id>/', todo_detail, name='todo_detail'),
    path('<int:todo_id>/update/', todo_update, name='todo_update'),
    path('<int:todo_id>/validate/', todo_validate, name='todo_validate'),
    path('<int:todo_id>/complete/', todo_complete, name='todo_complete'),
    path('create/', todo_create, name='todo_create'),
]

zcabinet/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls', namespace='todo')),
    path('gestions-budget/', include('gestionbuget.urls', namespace='gestionbudget')),
    path('gestions-budget/resumes/', include('resume.urls', namespace='resume')),
    # path('lawyer/', include('lawyer.urls', namespace='lawyer')),
    # path('gestiondoc/', include('gestiondoc.urls', namespace='gestiondoc')),
    # path("gestions-timer/", include("gestiontimer.urls", namespace="gestiontimer")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('customuser.urls', namespace='customuser')),

]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lawyer/models.py
from django.db import models

# Create your models here.

Type_champs = (
    ("charField", "Champ de type texte"),
    ("textField", "Champ de type texte long"),
    ("integerField", "Champ de type entier"),
    ("dateField", "Champ de type date"),
    ("booleanField", "Champ de type booléen"),
    ("emailField", "Champ de type email"),
    ("fileField", "Champ de type fichier"),
    ("imageField", "Champ de type image"),
    ("urlField", "Champ de type URL"),
    ("floatField", "Champ de type nombre à virgule flottante"),
    ("decimalField", "Champ de type nombre décimal"),
    ("timeField", "Champ de type heure"),
    ("dateTimeField", "Champ de type date et heure"),
    ("foreignKey", "Champ de type clé étrangère"),
    ("manyToManyField", "Champ de type plusieurs à plusieurs"),
    ("oneToOneField", "Champ de type un à un"),
)

### partie gestion de l'activité
class Champs(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    is_active = models.BooleanField(default=True)
    type_champs = models.CharField(choices=Type_champs, max_length=50, default=Type_champs[0][0])
    required = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class TypeActivity(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    
    champs = models.ManyToManyField(Champs, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class CategoryActivity(models.Model):
    type_activity = models.OneToOneField(TypeActivity, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class SubCategory(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    status = models.BooleanField(default=True)

    category = models.ForeignKey(CategoryActivity, related_name="sub_categorie", on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

lawyer/views.py
from django.shortcuts import render

# Create your views here.

lawyer/templates/lawyer/activiter/htmx/add_activity.html
<div x-data x-init="defInit( {{initialChamps}} )" class="h-full" id="liste_activiter">
    <form hx-post="{% url 'lawyer:add_type_activiter' %}" hx-target="#liste_activiter" hx-trigger="submit" hx-swap="outerHTML"
        hx-oob class="space-y-6">
        {% csrf_token %}
        <div>
            <label for="nom_activiter" class="block text-sm font-medium text-gray-700">Nom de l'activité</label>
            <div class="mt-1">
                <input type="text" name="name" id="nom_activiter" required
                autocomplete="given-name" class="block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none
                    focus:ring-blue-500 focus:border-blue-500 sm:text-sm" />
            </div>
        </div>
    
        <div class="space-y-6">
            <div>
            <h3 class="text-lg font-semibold ">Selectionner les champs</h3>
            <span class="text-sm text-gray-500">ajouter les champs qui seront affichés dans le formulaire</span>
            </div>
    
            <div class="space-y-4 max-h-96 overflow-y-auto">
                {% if error %}
                  <p class="text-red-500">{{ error }}</p>
                {% endif %}
                {% for champ in champs %}
                    <div class="flex justify-between items-center gap-2 px-4 py-2 border rounded-md ">
                        <div>
                            <p>{{ champ.name }}</p>
                            <span class="text-sm text-gray-500">{{ champ.description }}</span>
                        </div>
    
                        <div class="flex items-center gap-2">
                            <div x-data="{ switchOn: active_champs({{ champ.id }}) }" class="flex items-center justify-center space-x-2">
                                <label @click="$refs.switchButton.click(); $refs.switchButton.focus()" :id="$id('switch')"
                                    :class="{ 'text-blue-600': switchOn, 'text-gray-400': ! switchOn }"
                                    class="text-sm select-none"
                                    x-cloak>
                                    status
                                </label>
                                <button
                                    x-ref="switchButton"
                                    type="button"
                                    @click="switchOn = ! switchOn; switchOn ? addChamp({{ champ.id }}) : removeChamp({{ champ.id }})"
                                    :class="switchOn ? 'bg-blue-600' : 'bg-neutral-200'"
                                    class="relative inline-flex h-6 py-0.5 ml-4 focus:outline-none rounded-full w-10"
                                    x-cloak>
                                    <span :class="switchOn ? 'translate-x-[18px]' : 'translate-x-0.5'" class="w-5 h-5 duration-200 ease-in-out
                                        bg-white rounded-full shadow-md"></span>
                                </button>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <input type="text" name="champs" :value="getchamps" hidden>
        <div class="pt-5">
            <div class="flex justify-between items-center">
                <button type="button" @click="slideOverOpen=false" class="bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700
                    hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">Cancel</button>
                    <span x-text="getchamps"></span>
                <button type="submit" class="ml-3 inline-flex justify-center py-2 px-6 border border-transparent shadow-sm text-sm 
                font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2
                    focus:ring-blue-500">Sauvegarder</button>
            </div>  
        </div>
    </form>
</div>

{% if type_activity %}
  <div x-ref="tabButtons" class="relative flex items-center justify-center w-full h-10   p-1 text-gray-500 bg-white border 
    border-gray-100 rounded-lg select-none" id="Tabsheaders" hx-swap-oob="beforeend">
     
    <button :id="$id(tabId)" @click="tabButtonClicked($el);" type="button" :class="{ 'bg-gray-100 text-gray-700' : tabButtonActive($el) }" 
    class="relative z-20 inline-flex items-center justify-center w-full h-8 px-3 text-sm font-medium transition-all rounded-md
    cursor-pointer whitespace-nowrap">{{ type_activity.name }}</button>
  </div>

  <div class="relative flex items-center justify-center w-full p-5 mt-2 text-xs text-gray-400 border rounded-md 
    content border-gray-200/70" id="Tabsbody" hx-swap-oob="beforeend">
    <div :id="$id(tabId + '-content')" x-show="tabContentActive($el)" class="relative">
        This is the content shown for {{ type_activity.name }}
    </div>
  </div>
      
{% endif %}

lawyer/templates/lawyer/activiter/htmx/details_type_activiter.html
<div class="w-full">
    <div x-data="{ 
        activeAccordion: '', 
        setActiveAccordion(id) { 
            this.activeAccordion = (this.activeAccordion == id) ? '' : id 
        } 
    }" class="relative w-full mx-auto overflow-hidden text-sm font-normal  divide-y divide-gray-200 rounded-md">
        <div x-data="{ id: $id('accordion') }" class="cursor-pointer group">
            <button @click="setActiveAccordion(id)" class="flex items-center justify-between w-full p-4 gap-6 text-left select-none group-hover:underline">
                <span>    Voir la liste champs </span>
                <svg class="w-4 h-4 duration-200 ease-out" :class="{ 'rotate-180': activeAccordion==id }" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="6 9 12 15 18 9"></polyline></svg>
            </button>
            <div x-show="activeAccordion==id" x-collapse x-cloak>
                <div class="p-4 pt-0 mb-8 opacity-70 grid grid-cols-2 gap-8 ">
                    <div class="shadow-md py-6 px-3 rounded-lg space-y-4 bg-teal-50">
                        <h3 class="text-lg font-semibold text-blue-600">Champs actif</h3>
                        <div class="space-y-3" id="champ_active">
                            {% for champs  in used_champs %}
                                <div class="flex justify-between items-center gap-2 px-4 py-2 border border-gray-900
                                text-base rounded-md "
                                id="champ_{{champs.id}}"
                                >
                                    <div>
                                        <p>{{champs.name}}</p>
                                        <span class="text-sm text-gray-700">{{champs.description}}</span>
                                    </div>
                                    <div>
                                        <form class="flex items-center gap-2"
                                        hx-post="{% url 'lawyer:active_champs_types' type_activity.id champs.id %}"
                                        hx-target="#champ_{{champs.id}}" hx-trigger="submit" hx-swap="outerHTML">
                                            <div x-data="{ switchOn: true }" class="flex items-center justify-center space-x-4">
                                                <input id="thisId" type="checkbox" name="status" class="hidden" :checked="switchOn">
                                                <label @click="$refs.switchButton.click(); $refs.switchButton.focus()" :id="$id('switch')" 
                                                    :class="{ 'text-blue-600': switchOn, 'text-gray-700': ! switchOn }"
                                                    class="text-xs font-medium select-none"
                                                    x-cloak>
                                                    Status
                                                </label>
                                                <button 
                                                    x-ref="switchButton"
                                                    type="submit" 
                                                    @click="switchOn = ! switchOn"
                                                    :class="switchOn ? 'bg-blue-600' : 'bg-neutral-200'" 
                                                    class="relative inline-flex h-4 py-0.5 ml-4 rounded-full focus:outline-none w-8"
                                                    x-cloak>
                                                    <span :class="switchOn ? 'translate-x-[18px]' : 'translate-x-0.5'" class="w-3 h-3 duration-200 ease-in-out bg-white rounded-full shadow-md"></span>
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="space-y-4">
                        <h3 class="text-lg font-semibold">Champs inactif</h3>
                        <div class="space-y-3" id="champ_inactive">
                            {% for champs  in unused_champs %}
                            <div class="flex justify-between items-center gap-2 px-4 py-2 border rounded-md "
                            id="champ_in_{{champs.id}}">
                                <div>
                                    <p>{{champs.name}}</p>
                                    <span class="text-sm text-gray-500">{{champs.name}}</span>
                                </div>
                                <div>
                                    <div class="flex items-center gap-2">
                                        <form x-data="{ switchOn: false }" class="flex items-center justify-center space-x-4"
                                        hx-post="{% url 'lawyer:active_champs_types' type_activity.id champs.id %}" 
                                        hx-target="#champ_in_{{champs.id}}" hx-trigger="submit" hx-swap="outerHTML"
                                        >
                                            <input id="thisId" type="checkbox" name="status" class="hidden" :checked="switchOn">
                                            <label @click="$refs.switchButton.click(); $refs.switchButton.focus()" :id="$id('switch')" 
                                                :class="{ 'text-blue-600': switchOn, 'text-gray-400': ! switchOn }"
                                                class="text-xs font-medium select-none"
                                                x-cloak>
                                                Status
                                            </label>
                                            <button 
                                                x-ref="switchButton"
                                                type="submit" 
                                                @click="switchOn = ! switchOn"
                                                :class="switchOn ? 'bg-blue-600' : 'bg-neutral-200'" 
                                                class="relative inline-flex h-4 py-0.5 ml-4 rounded-full focus:outline-none w-8"
                                                x-cloak>
                                                <span :class="switchOn ? 'translate-x-[18px]' : 'translate-x-0.5'" class="w-3 h-3 duration-200 ease-in-out bg-white rounded-full shadow-md"></span>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% if categorie %}
    <div class="w-full space-y-3">
        <h3 class="text-base">Catégories</h3>

        <div class="w-full grid grid-cols-2 gap-8">
            <div class="space-y-3" id="activity_category">
                {% for cates in type_activity.categoryactivity.sub_categorie.all %}
                <div class="flex justify-between items-center gap-2 px-4 py-2 border rounded-md ">
                    <div>
                        <p>{{cates.name}}</p>
                        <span class="text-sm text-gray-500">{{cates.description}} </span>
                    </div>
                    <div>
                        <div class="flex items-center gap-2">
                            <div x-data="{ switchOn: {% if cates.status %} true {% else %} false {% endif %} }" 
                            class="flex items-center justify-center space-x-4">
                                <input id="thisId" type="checkbox" name="switch" class="hidden" :checked="switchOn" 
                                >
                                <label @click="$refs.switchButton.click(); $refs.switchButton.focus()" :id="$id('switch')" 
                                    :class="{ 'text-neutral-900': switchOn, 'text-gray-400': ! switchOn }"
                                    class="text-xs font-medium select-none"
                                    x-cloak>
                                    Status
                                </label>
                                <button 
                                    x-ref="switchButton"
                                    type="button" 
                                    @click="switchOn = ! switchOn"
                                    :class="switchOn ? 'bg-neutral-900' : 'bg-neutral-200'" 
                                    class="relative inline-flex h-4 py-0.5 ml-4 rounded-full focus:outline-none w-8"
                                    x-cloak>
                                    <span :class="switchOn ? 'translate-x-[18px]' : 'translate-x-0.5'" class="w-3 h-3 duration-200 ease-in-out bg-white rounded-full shadow-md"></span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

            <div class="flex justify-center px-8 gap-3">
                
                <div class="w-4/5 border rounded-md flex flex-col gap-3 px-2 py-4">
                     <h4 class="text-lg font-semibold text-center">Ajouter une categorie</h4>

                     <form hx-post="{% url 'lawyer:add_categorie_activity' type_activity.id %}"
                     hx-target="#activity_category" hx-swap="afterbegin" hx-trigger="submit"
                     class="flex flex-col gap-4">
                        <div class="flex flex-col text-base px-3">
                            <label for="name">Nom </label>
                            <input type="text" name="name" class="
                            px-3 py-2 rounded-md text-base">
                        </div>

                        <div class="flex flex-col text-base px-3">
                            <label for="description">Description</label>
                            <textarea name="description" id=""
                            class="px-3 py-2 rounded-md text-base min-h-52"></textarea>
                        </div>

                        <div class="w-full px-3">
                            <button class="w-full lawyer-btn-primary flex justify-center">Ajouter</button>
                        </div>
                     </form>
                </div>
                
            </div>
        </div>
    </div>
    {% endif %}
</div>